### PR TITLE
added a dynamic footer #132 and updated unit test to adhere to the ca…

### LINKED ISSUE #132: Copyright update in the footer before official release!
## Type of Change
- [ ] New Feature Request
- [ X ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Awesome presentation Owen and great job everyone!

For the release, do you want copyright 2018 in the footer instead of 2017? 😁

screenshot_20180118-193356

### PR DESCRIPTION
**Pull request by MichaelNeas**
…Fixing my own issue for dynamic year in footer

## Related Issue
closes #132

## Summary of Changes
1. [x] footer.jsx - new date
1. [x] footer.spec.jsx - update to reflect whats being rendered on page

### CODE REVIEW

**Comment by thescientist13** [comment]
Working out preferred implementation in the issue

**Comment by MichaelNeas** [comment]
@thescientist13 Thanks for the recommendation, and I apologize for not fully abiding by the contribution requirements! It's also totally fine if you want to toss the PR if you'd like, I didn't mean for this to be a hassle haha. I usually don't even put Copyright in the footer of websites I build out 😄, I would however argue to update that unit test description for the footer copyright if you decide to close the PR.

**Comment by thescientist13** [comment]
@MichaelNeas 
No worries, I just wanted to give you a heads up to a best practice.  

I'll make a decision either way but I think we're leaning towards removing the copyright, so that's likely what I'll have you do, so need to toss this PR away just yet!

No hassle, I appreciate you raising the issue, and the discussion on copyrights in Slack was a valuable one to the community I feel.  This all part of the OSS / development process and experience!   😃

**Comment by thescientist13** [comment]
@MichaelNeas 
Just a heads up that your branch here will need to be (ideally) rebased against the upstream develop branch now that the changes in #136 have been merged.

If you have any questions on those git workflows, let me know!  (preferable via one the Slack channels, so I the knowledge can be distributed)

**Comment by MichaelNeas** [comment]
@thescientist13 Hopefully this updated pr can close out the issue and the pr 😄

**Pull request merged**
