### PR TITLE
lazy load card images

### LINKED ISSUE #75: lazy load images to improve Lighthouse performance score (Lighthouse round 3)
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Continuing from #59 / #69 / #72 there are now recommendations for image loading, this wasn't so much an issue before but as merged #68 at the same time as #72 , it basically offset our gain.  

Some of these images come from Meetup.com, so that may impact the full extent of what we can do here.

### Current Lighthouse score at time of this ticket
screen shot 2017-11-20 at 8 44 59 pm

### Lighthouse Recommendations
screen shot 2017-11-20 at 8 45 08 pm

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue

resolves #75 (and #79)

## Summary of Changes

1. `LazyLoad` `` tag in the `Card` component 
1.  Placeholder image saved locally and bundled with webpack instead of via HTTP request
1.  Use `CSSTransitionGroup` to fade in images on `entered`.  Best guess since external image loading can succumb to various factors, but this seemed to implement a nice fade > 90% of the time if the image itself loaded in < 500ms
1.  Added [`ModuleConcatationPlugin`](https://webpack.js.org/plugins/module-concatenation-plugin/) from **webpack** to get scope hoisting
1.  Added sourcemaps for development
1.  Added tests for all components within `<LazyLoad>` ( #79 )

### CODE REVIEW

**Comment by thescientist13** [comment]
Commented on this about how to test our `` tag
https://github.com/jasonslyvia/react-lazyload/issues/120

**Comment by paul-barry-kenzan** [comment]
If you classified the LazyLoad as implementation details, and you focus on the rendering of the image itself, you could abstract the `` generation and test the method output.

Similar to:
```javascript
generateImage () {
  return <img className="card-img" src={ this.props.imgSource } alt={ this.props.imgAlt } />
}

// within render() 
<LazyLoad height={233}>
  {generateImage()}
</LazyLoad>
```

Test(s) could be similar to:
```javascript
it('should return an image with the provided properties', () => {
  const img = card.instance().generateImage(); // this line may be incorrect, but you get the idea.

  expect(img.prop('src')).toEqual(mockCardContent.group.group_photo);
  expect(img.prop('alt')).toEqual(mockCardContent.name);
});
```

**Comment by thescientist13** [comment]
Great suggestion and thanks for chiming in @paul-barry-kenzan !

Your solution is definitely a step forward and is certainly better than not being able to test the `` tag at all so thank you for this!

I do hope I am able to find a solution so that I can take the next step and test / ensure that `` tags is nested within the `<LazyLoad>` element so I can get the best of both worlds.

**Comment by thescientist13** [comment]
So now locally I can see that if load the home page from the top
1. Only the hero banner image will be requested
1. Then as we scroll the next row of images load
1. And then at the bottom of the events list, the last new image load

That said, it might be nice to see if there's a way to fade the images in.

**Comment by thescientist13** [comment]
Now with fading!  🎉 
lazy-load-fade-in-console

Note: the fade in can only do so much where if the image takes a long time to download from the server, it might still "pop" into view.  Right now, the component will give the image up to 500ms before starting the transition.  Risks are if we wait too long, or start too soon, we'll get nothing, so based on the times I was seeing, 500ms seems about tight.

**Pull request merged**
