### PR TITLE
Add events list mobile fix

### PR DESCRIPTION
**Pull request by Peter-holyoke**
## Related Issue

https://github.com/ProvidenceGeeks/website-frontend/issues/65

## Summary of Changes

Made changes to the card component, events-list component and navigation-bar tab container to reflect mobile application design for the events list.

### CODE REVIEW

**Comment by Peter-holyoke** [comment]
My reasoning behind that specific override is that the card will probably be used differently depending on where it is being used. In the context of the events list, the margin I set is appropriate, but may not be elsewhere. 

But, I don't think it would hurt to move this into the card component either, since the user could just override it.

**Comment by thescientist13** [comment]
@Peter-holyoke 
Yeah, if the overrides aren't specific to the Bootstrap implementation, but rather just contextualizing  for the `EventsList` component, then that seems fine.  

If we ever needed some sort of generic reset against the Bootstrap `_card.scss` then yeah, that seems like the right time to capture it in the `Card` component's CSS.

**Comment by thescientist13** [comment]
@Peter-holyoke 
Looking at how **@ Warwick** and **@ Providence
screen shot 2017-11-17 at 11 49 35 am
** break onto the next line

Seems to be a line-height or vertical alignment issue related to trying to maintain good alignment with the sub-heading and the icons?

Anything you think we can do to tweak it so the gap isn't so big?

**Comment by Peter-holyoke** [comment]
@thescientist13 How does this look? 

screen shot 2017-11-17 at 11 54 11 am

**Comment by thescientist13** [comment]
Looks great @Peter-holyoke !

**Pull request merged**
